spring.application.name=content-service
content.storage.local.base-path=${STORAGE_PATH:/home/ahmed-yassine/Desktop/udemy-clone/backend/uploads}
content.storage.local.base-url=${STORAGE_BASE_URL:http://localhost:8084}
